tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
brew "openjdk"
brew "syncthing", restart_service: true
brew "yadm"
brew "zsh"
cask "android-platform-tools"
cask "authy"
cask "bettertouchtool"
cask "firefox-nightly"
cask "iina"
cask "intellij-idea-ce"
cask "iterm2"
cask "spotify"
cask "visual-studio-code"
